import random
import datetime

def escape(s):
    return s.replace("'", "''")

def main():
    sql = []
    
    # 1.1 DDL
    sql.append("-- ===========================================")
    sql.append("-- 1.1 DDL: CREACIÓN DEL ESQUEMA FÍSICO")
    sql.append("-- ===========================================")
    sql.append("DROP DATABASE IF EXISTS PEDIDOS;")
    sql.append("CREATE DATABASE PEDIDOS CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    sql.append("USE PEDIDOS;")
    sql.append("")
    sql.append("CREATE TABLE Proveedores (")
    sql.append("    idproveedor INT AUTO_INCREMENT PRIMARY KEY,")
    sql.append("    nombre_proveedor VARCHAR(100) NOT NULL,")
    sql.append("    direccion VARCHAR(200),")
    sql.append("    mail VARCHAR(100) NOT NULL UNIQUE")
    sql.append(");")
    sql.append("")
    sql.append("CREATE TABLE Clientes (")
    sql.append("    idcliente INT AUTO_INCREMENT PRIMARY KEY,")
    sql.append("    apellido VARCHAR(50) NOT NULL,")
    sql.append("    nombres VARCHAR(50) NOT NULL,")
    sql.append("    direccion VARCHAR(200),")
    sql.append("    mail VARCHAR(100) NOT NULL UNIQUE")
    sql.append(");")
    sql.append("")
    sql.append("CREATE TABLE Vendedor (")
    sql.append("    idvendedor INT AUTO_INCREMENT PRIMARY KEY,")
    sql.append("    apellido VARCHAR(50) NOT NULL,")
    sql.append("    nombres VARCHAR(50) NOT NULL,")
    sql.append("    mail VARCHAR(100) NOT NULL UNIQUE,")
    sql.append("    comision DECIMAL(5,2) CHECK (comision >= 0 AND comision <= 100)")
    sql.append(");")
    sql.append("")
    sql.append("CREATE TABLE Productos (")
    sql.append("    idproducto INT AUTO_INCREMENT PRIMARY KEY,")
    sql.append("    descripcion VARCHAR(200) NOT NULL,")
    sql.append("    precio_unitario DECIMAL(10,2) CHECK (precio_unitario >= 0),")
    sql.append("    stock INT CHECK (stock >= 0),")
    sql.append("    stock_max INT,")
    sql.append("    stock_min INT,")
    sql.append("    idproveedor INT,")
    sql.append("    origen VARCHAR(20) CHECK (origen IN ('Nacional', 'Importado')),")
    sql.append("    FOREIGN KEY (idproveedor) REFERENCES Proveedores(idproveedor) ON DELETE RESTRICT ON UPDATE CASCADE")
    sql.append(");")
    sql.append("")
    sql.append("CREATE TABLE Pedidos (")
    sql.append("    numero_pedido INT AUTO_INCREMENT PRIMARY KEY,")
    sql.append("    idcliente INT,")
    sql.append("    idvendedor INT,")
    sql.append("    fecha DATE NOT NULL,")
    sql.append("    estado VARCHAR(20) CHECK (estado IN ('CONFIRMADO', 'ANULADO', 'PENDIENTE')),")
    sql.append("    FOREIGN KEY (idcliente) REFERENCES Clientes(idcliente) ON DELETE RESTRICT ON UPDATE CASCADE,")
    sql.append("    FOREIGN KEY (idvendedor) REFERENCES Vendedor(idvendedor) ON DELETE RESTRICT ON UPDATE CASCADE")
    sql.append(");")
    sql.append("")
    sql.append("CREATE TABLE Detalle_Pedidos (")
    sql.append("    numero_pedido INT,")
    sql.append("    renglon INT,")
    sql.append("    idproducto INT,")
    sql.append("    cantidad INT CHECK (cantidad > 0),")
    sql.append("    precio_unitario DECIMAL(10,2),")
    sql.append("    total DECIMAL(12,2),")
    sql.append("    PRIMARY KEY (numero_pedido, renglon),")
    sql.append("    FOREIGN KEY (numero_pedido) REFERENCES Pedidos(numero_pedido) ON DELETE RESTRICT ON UPDATE CASCADE,")
    sql.append("    FOREIGN KEY (idproducto) REFERENCES Productos(idproducto) ON DELETE RESTRICT ON UPDATE CASCADE")
    sql.append(");")
    sql.append("")
    
    # 1.2 DML
    sql.append("-- ===========================================")
    sql.append("-- 1.2 DML: POBLADO MASIVO DE DATOS (INSERTs)")
    sql.append("-- (Se usan inserciones múltiples para reducir el log en consola)")
    sql.append("-- ===========================================")
    
    # Proveedores (10)
    sql.append("-- Proveedores")
    sql.append("INSERT INTO Proveedores (nombre_proveedor, direccion, mail) VALUES")
    vals = []
    for i in range(1, 11):
        nombre = f"Proveedor Tech {i} S.A."
        dir_ = f"Calle Proveedor {i * 100}"
        mail = f"contacto@proveedortech{i}.com.ar"
        vals.append(f"('{escape(nombre)}', '{escape(dir_)}', '{escape(mail)}')")
    sql.append(",\n".join(vals) + ";\n")
    
    # Vendedores (10)
    sql.append("-- Vendedores")
    sql.append("INSERT INTO Vendedor (apellido, nombres, mail, comision) VALUES")
    apellidos_v = ["Gomez", "Lopez", "Perez", "Rodriguez", "Fernandez", "Garcia", "Martinez", "Sanchez", "Romero", "Sosa"]
    nombres_v = ["Juan", "Maria", "Pedro", "Ana", "Luis", "Laura", "Carlos", "Marta", "Diego", "Sofia"]
    vals = []
    for i in range(1, 11):
        ape = apellidos_v[i-1]
        nom = nombres_v[i-1]
        mail = f"{nom.lower()}.{ape.lower()}@ventas.com"
        comision = round(random.uniform(1.0, 15.0), 2)
        vals.append(f"('{escape(ape)}', '{escape(nom)}', '{escape(mail)}', {comision})")
    sql.append(",\n".join(vals) + ";\n")
    
    # Clientes (50)
    sql.append("-- Clientes")
    sql.append("INSERT INTO Clientes (apellido, nombres, direccion, mail) VALUES")
    apellidos_c = ["Diaz", "Ruiz", "Alvarez", "Gimenez", "Torres", "Dominguez", "Vargas", "Ramos", "Castro", "Suarez"]
    nombres_c = ["Lucia", "Jorge", "Camila", "Marcos", "Valentina", "Facundo", "Micaela", "Matias", "Julieta", "Nicolas"]
    vals = []
    for i in range(1, 51):
        ape = random.choice(apellidos_c)
        nom = random.choice(nombres_c)
        dir_ = f"Av. Cliente {i * 10}, CABA"
        mail = f"cliente{i}_{nom.lower()}{ape.lower()}@ejemplo.com"
        vals.append(f"('{escape(ape)}', '{escape(nom)}', '{escape(dir_)}', '{escape(mail)}')")
    sql.append(",\n".join(vals) + ";\n")
    
    # Productos (100)
    sql.append("-- Productos")
    sql.append("INSERT INTO Productos (descripcion, precio_unitario, stock, stock_max, stock_min, idproveedor, origen) VALUES")
    productos_tipos = ["Notebook", "Mouse", "Teclado", "Monitor", "Placa de Video", "Memoria RAM", "Disco Solido SSD", "Gabinete", "Fuente", "Auriculares"]
    productos_precios = {}
    vals = []
    for i in range(1, 101):
        tipo = random.choice(productos_tipos)
        desc = f"{tipo} Modelo {random.randint(100, 999)} - Version {random.choice(['Pro', 'Lite', 'Gaming', 'Office'])}"
        precio = round(random.uniform(5000, 1500000), 2)
        stock_min = random.randint(5, 20)
        stock_max = random.randint(50, 200)
        stock = random.randint(stock_min + 1, stock_max - 1)
        idproveedor = random.randint(1, 10)
        origen = random.choice(['Nacional', 'Importado'])
        
        productos_precios[i] = precio
        vals.append(f"('{escape(desc)}', {precio}, {stock}, {stock_max}, {stock_min}, {idproveedor}, '{origen}')")
    sql.append(",\n".join(vals) + ";\n")
    
    # Pedidos (200)
    sql.append("-- Pedidos")
    sql.append("INSERT INTO Pedidos (idcliente, idvendedor, fecha, estado) VALUES")
    start_date = datetime.date(2023, 8, 1)
    end_date = datetime.date(2024, 8, 1)
    time_between_dates = end_date - start_date
    days_between_dates = time_between_dates.days
    vals = []
    for i in range(1, 201):
        idcliente = random.randint(1, 50)
        idvendedor = random.randint(1, 10)
        random_number_of_days = random.randrange(days_between_dates)
        fecha = start_date + datetime.timedelta(days=random_number_of_days)
        estado = random.choice(['CONFIRMADO', 'ANULADO', 'PENDIENTE'])
        vals.append(f"({idcliente}, {idvendedor}, '{fecha}', '{estado}')")
    sql.append(",\n".join(vals) + ";\n")
        
    # Detalle_Pedidos (1-4 por pedido)
    sql.append("-- Detalle_Pedidos")
    sql.append("INSERT INTO Detalle_Pedidos (numero_pedido, renglon, idproducto, cantidad, precio_unitario, total) VALUES")
    vals = []
    for id_pedido in range(1, 201):
        num_renglones = random.randint(1, 4)
        productos_usados = set()
        for renglon in range(1, num_renglones + 1):
            idproducto = random.randint(1, 100)
            while idproducto in productos_usados:
                idproducto = random.randint(1, 100)
            productos_usados.add(idproducto)
            
            cantidad = random.randint(1, 5)
            precio_unitario = productos_precios[idproducto]
            total = round(cantidad * precio_unitario, 2)
            vals.append(f"({id_pedido}, {renglon}, {idproducto}, {cantidad}, {precio_unitario}, {total})")
    sql.append(",\n".join(vals) + ";\n")
    
    sql.append("-- ===========================================")
    sql.append("-- SELECT COUNT para verificación")
    sql.append("-- ===========================================")
    sql.append("SELECT 'Proveedores' AS Tabla, COUNT(*) AS Total FROM Proveedores;")
    sql.append("SELECT 'Clientes' AS Tabla, COUNT(*) AS Total FROM Clientes;")
    sql.append("SELECT 'Vendedor' AS Tabla, COUNT(*) AS Total FROM Vendedor;")
    sql.append("SELECT 'Productos' AS Tabla, COUNT(*) AS Total FROM Productos;")
    sql.append("SELECT 'Pedidos' AS Tabla, COUNT(*) AS Total FROM Pedidos;")
    sql.append("SELECT 'Detalle_Pedidos' AS Tabla, COUNT(*) AS Total FROM Detalle_Pedidos;")
    sql.append("")

    sql.append("-- ===========================================")
    sql.append("-- 1.3 DEFINICIÓN DE VISTAS DE NEGOCIO")
    sql.append("-- ===========================================")
    sql.append("CREATE OR REPLACE VIEW vw_clientes_activos AS")
    sql.append("SELECT DISTINCT c.idcliente, c.apellido, c.nombres, c.mail, p.fecha")
    sql.append("FROM Clientes c")
    sql.append("JOIN Pedidos p ON c.idcliente = p.idcliente")
    sql.append("WHERE p.fecha >= DATE_SUB(CURDATE(), INTERVAL 1 YEAR);")
    sql.append("")
    sql.append("CREATE OR REPLACE VIEW vw_rendimiento_vendedores AS")
    sql.append("SELECT v.idvendedor, v.apellido, v.nombres, COUNT(p.numero_pedido) AS total_pedidos")
    sql.append("FROM Vendedor v")
    sql.append("LEFT JOIN Pedidos p ON v.idvendedor = p.idvendedor")
    sql.append("GROUP BY v.idvendedor, v.apellido, v.nombres")
    sql.append("ORDER BY total_pedidos DESC;")
    sql.append("")
    sql.append("CREATE OR REPLACE VIEW vw_pedidos_alto_valor AS")
    sql.append("SELECT p.numero_pedido, SUM(dp.total) AS importe_total")
    sql.append("FROM Pedidos p")
    sql.append("JOIN Detalle_Pedidos dp ON p.numero_pedido = dp.numero_pedido")
    sql.append("GROUP BY p.numero_pedido")
    sql.append("HAVING importe_total > 500000;")
    sql.append("")
    sql.append("CREATE OR REPLACE VIEW vw_productos_vendidos_periodo AS")
    sql.append("SELECT pr.origen, pr.idproducto, pr.descripcion, SUM(dp.cantidad) AS total_unidades, p.fecha")
    sql.append("FROM Productos pr")
    sql.append("JOIN Detalle_Pedidos dp ON pr.idproducto = dp.idproducto")
    sql.append("JOIN Pedidos p ON dp.numero_pedido = p.numero_pedido")
    sql.append("GROUP BY pr.origen, pr.idproducto, pr.descripcion, p.fecha;")
    sql.append("")
    sql.append("CREATE OR REPLACE VIEW vw_clientes_sin_pedidos AS")
    sql.append("SELECT * FROM Clientes WHERE idcliente NOT IN (SELECT idcliente FROM Pedidos);")
    sql.append("")
    sql.append("CREATE OR REPLACE VIEW vw_clientes_ocacionales AS")
    sql.append("SELECT c.idcliente, c.apellido, c.nombres, COUNT(p.numero_pedido) AS total_pedidos")
    sql.append("FROM Clientes c")
    sql.append("LEFT JOIN Pedidos p ON c.idcliente = p.idcliente")
    sql.append("GROUP BY c.idcliente, c.apellido, c.nombres")
    sql.append("HAVING total_pedidos < 2;")
    sql.append("")

    sql.append("-- ===========================================")
    sql.append("-- 1.4 SEGURIDAD Y CONTROL DE ACCESO (DCL)")
    sql.append("-- ===========================================")
    sql.append("DROP ROLE IF EXISTS rol_auditor, rol_vendedor, rol_admin;")
    sql.append("CREATE ROLE rol_auditor;")
    sql.append("CREATE ROLE rol_vendedor;")
    sql.append("CREATE ROLE rol_admin;")
    sql.append("")
    sql.append("GRANT SELECT ON PEDIDOS.* TO rol_auditor;")
    sql.append("GRANT SELECT, UPDATE ON PEDIDOS.Clientes TO rol_vendedor;")
    sql.append("GRANT SELECT, UPDATE, INSERT ON PEDIDOS.Pedidos TO rol_vendedor;")
    sql.append("GRANT SELECT, UPDATE, INSERT ON PEDIDOS.Detalle_Pedidos TO rol_vendedor;")
    sql.append("GRANT ALL PRIVILEGES ON PEDIDOS.* TO rol_admin;")
    sql.append("")
    sql.append("DROP USER IF EXISTS 'usuario_auditoria'@'localhost', 'usuario_ventas1'@'localhost', 'usuario_admin1'@'localhost';")
    sql.append("CREATE USER 'usuario_auditoria'@'localhost' IDENTIFIED BY 'Pass1234!';")
    sql.append("CREATE USER 'usuario_ventas1'@'localhost' IDENTIFIED BY 'Pass1234!';")
    sql.append("CREATE USER 'usuario_admin1'@'localhost' IDENTIFIED BY 'Pass1234!';")
    sql.append("")
    sql.append("GRANT rol_auditor TO 'usuario_auditoria'@'localhost';")
    sql.append("GRANT rol_vendedor TO 'usuario_ventas1'@'localhost';")
    sql.append("GRANT rol_admin TO 'usuario_admin1'@'localhost';")
    sql.append("")
    sql.append("SET DEFAULT ROLE rol_auditor TO 'usuario_auditoria'@'localhost';")
    sql.append("SET DEFAULT ROLE rol_vendedor TO 'usuario_ventas1'@'localhost';")
    sql.append("SET DEFAULT ROLE rol_admin TO 'usuario_admin1'@'localhost';")
    sql.append("FLUSH PRIVILEGES;")
    sql.append("")

    sql.append("-- ===========================================")
    sql.append("-- 1.5 PLANES DE EJECUCIÓN E INDEXACIÓN")
    sql.append("-- ===========================================")
    sql.append("-- Consulta de analisis original:")
    sql.append("EXPLAIN")
    sql.append("SELECT p.descripcion, SUM(dp.cantidad) AS total_vendido")
    sql.append("FROM Productos p")
    sql.append("JOIN Detalle_Pedidos dp ON p.idproducto = dp.idproducto")
    sql.append("JOIN Pedidos pe ON dp.numero_pedido = pe.numero_pedido")
    sql.append("WHERE pe.fecha BETWEEN '2024-01-01' AND '2024-06-30'")
    sql.append(" AND p.origen = 'Importado'")
    sql.append("GROUP BY p.descripcion")
    sql.append("ORDER BY total_vendido DESC;")
    sql.append("")
    sql.append("-- Creación de índices secundarios para optimizar filtro por fecha y origen")
    sql.append("CREATE INDEX idx_pedidos_fecha ON Pedidos(fecha);")
    sql.append("CREATE INDEX idx_productos_origen ON Productos(origen);")
    sql.append("")
    sql.append("-- Consulta con EXPLAIN después de optimización:")
    sql.append("EXPLAIN")
    sql.append("SELECT p.descripcion, SUM(dp.cantidad) AS total_vendido")
    sql.append("FROM Productos p")
    sql.append("JOIN Detalle_Pedidos dp ON p.idproducto = dp.idproducto")
    sql.append("JOIN Pedidos pe ON dp.numero_pedido = pe.numero_pedido")
    sql.append("WHERE pe.fecha BETWEEN '2024-01-01' AND '2024-06-30'")
    sql.append(" AND p.origen = 'Importado'")
    sql.append("GROUP BY p.descripcion")
    sql.append("ORDER BY total_vendido DESC;")
    sql.append("")

    sql.append("-- ===========================================")
    sql.append("-- 1.6 TRANSACCIONES ACID (BLOQUES SQL DIRECTOS)")
    sql.append("-- ===========================================")
    sql.append("-- Escenario A (Caso Exitoso - Commit)")
    sql.append("START TRANSACTION;")
    sql.append("INSERT INTO Pedidos (idcliente, idvendedor, fecha, estado) VALUES (1, 1, CURDATE(), 'CONFIRMADO');")
    sql.append("SET @ult_pedido = LAST_INSERT_ID();")
    sql.append("INSERT INTO Detalle_Pedidos (numero_pedido, renglon, idproducto, cantidad, precio_unitario, total)")
    sql.append("VALUES (@ult_pedido, 1, 1, 2, (SELECT precio_unitario FROM Productos WHERE idproducto = 1), 2 * (SELECT precio_unitario FROM Productos WHERE idproducto = 1));")
    sql.append("INSERT INTO Detalle_Pedidos (numero_pedido, renglon, idproducto, cantidad, precio_unitario, total)")
    sql.append("VALUES (@ult_pedido, 2, 2, 1, (SELECT precio_unitario FROM Productos WHERE idproducto = 2), 1 * (SELECT precio_unitario FROM Productos WHERE idproducto = 2));")
    sql.append("UPDATE Productos SET stock = stock - 2 WHERE idproducto = 1;")
    sql.append("UPDATE Productos SET stock = stock - 1 WHERE idproducto = 2;")
    sql.append("COMMIT;")
    sql.append("")
    sql.append("-- Escenario B (Caso con Fallo e Integridad - Rollback)")
    sql.append("START TRANSACTION;")
    sql.append("INSERT INTO Pedidos (idcliente, idvendedor, fecha, estado) VALUES (99999, 1, CURDATE(), 'CONFIRMADO'); -- ID Cliente inexistente")
    sql.append("-- Esto lanzara un error por FK, asi que hacemos ROLLBACK")
    sql.append("ROLLBACK;")
    sql.append("")
    sql.append("-- Escenario C (Puntos de Salvaguarda - Savepoint)")
    sql.append("START TRANSACTION;")
    sql.append("UPDATE Productos SET precio_unitario = precio_unitario * 1.10 WHERE idproducto = 3;")
    sql.append("SAVEPOINT punto1;")
    sql.append("UPDATE Productos SET stock = stock + 10 WHERE idproducto = 4;")
    sql.append("ROLLBACK TO SAVEPOINT punto1;")
    sql.append("COMMIT;")
    
    with open('entregable_pedidos.sql', 'w', encoding='utf-8') as f:
        f.write('\n'.join(sql))

if __name__ == '__main__':
    main()
