-- 1. Crear tabla de productos
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  sub_category TEXT,
  price NUMERIC NOT NULL,
  image_url TEXT,
  quick_add_upsell BOOLEAN DEFAULT false,
  has_free_packaging BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);



-- 3. Crear el Bucket de almacenamiento para las fotos de los productos
INSERT INTO storage.buckets (id, name, public) VALUES ('product-images', 'product-images', true);

-- 4. Configurar las políticas de seguridad del bucket (RLS)
-- Permitir a cualquiera ver las imágenes
CREATE POLICY "Public Access" ON storage.objects FOR SELECT TO public USING (bucket_id = 'product-images');
-- Permitir solo a los administradores logueados subir/editar/borrar imágenes
CREATE POLICY "Auth Upload" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'product-images');
CREATE POLICY "Auth Update" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'product-images');
CREATE POLICY "Auth Delete" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'product-images');

-- 5. Opcional: Desactivar RLS en la tabla products para simplificar (o crear políticas similares allí)
-- Ya que esta app usa admin y publico, dejemos las consultas públicas libres
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
-- Correr en el Supabase SQL Editor para implementar la base de carritos abandonados (Leads)

CREATE TABLE IF NOT EXISTS public.abandoned_carts (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    name TEXT,
    phone TEXT,
    cart_data JSONB NOT NULL,
    total NUMERIC,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.abandoned_carts ENABLE ROW LEVEL SECURITY;

-- Permite a cualquiera (público anónimo) INSERTAR y ACTUALIZAR un carrito (usando ON CONFLICT en email)
-- Para esto, permitimos INSERT y UPDATE público temporalmente, o mejor manejarlo del lado del server (API).
-- Si lo hacemos desde la API con el anon key, necesitamos políticas:

CREATE POLICY "Permitir inserción anónima" 
ON public.abandoned_carts FOR INSERT 
WITH CHECK (true);

CREATE POLICY "Permitir update anónimo" 
ON public.abandoned_carts FOR UPDATE 
USING (true)
WITH CHECK (true);
-- Ejecutalo en el Supabase SQL Editor para habilitar los nuevos botones del Panel

-- 1. Añadimos el botón toggle de si Mostrar la etiqueta de Últimas Unidades
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS show_stock_alert BOOLEAN DEFAULT false;

-- 2. Añadimos el botón toggle de si el producto es Prioridad en el Catálogo (Destacado)
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_priority BOOLEAN DEFAULT false;
-- Tabla para registrar analíticas de tráfico
CREATE TABLE IF NOT EXISTS public.page_views (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    session_id TEXT NOT NULL,
    path TEXT NOT NULL,
    duration_seconds INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Habilitar Políticas de Seguridad a Nivel de Fila (RLS)
ALTER TABLE public.page_views ENABLE ROW LEVEL SECURITY;

-- 1. Permitir que cualquier visitante (anónimo) registre su visita
CREATE POLICY "Permitir inserciones anonimas" ON public.page_views
    FOR INSERT WITH CHECK (true);

-- 2. Permitir que el visitante actualice el "tiempo de permanencia" al salir
CREATE POLICY "Permitir actualizaciones anonimas" ON public.page_views
    FOR UPDATE USING (true);

-- 3. Solo tú (el dueño autenticado) puedes leer/ver los datos en el Dashboard
CREATE POLICY "Permitir select autenticado admin" ON public.page_views
    FOR SELECT USING (auth.role() = 'authenticated');
-- ============================================================
--  Proyecto 3D — Analytics Events (Funnel Tracking)
--  Ejecutar en el SQL Editor de Supabase
-- ============================================================

-- 1. Tabla de eventos analíticos
CREATE TABLE IF NOT EXISTS public.analytics_events (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    session_id TEXT NOT NULL,
    event_name VARCHAR(50) NOT NULL,
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Índices para consultas rápidas
CREATE INDEX IF NOT EXISTS idx_events_name ON public.analytics_events (event_name);
CREATE INDEX IF NOT EXISTS idx_events_session ON public.analytics_events (session_id);
CREATE INDEX IF NOT EXISTS idx_events_created_at ON public.analytics_events (created_at DESC);

-- 3. Habilitar RLS
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;

-- 4. Permitir inserción pública anónima (los eventos se envían desde el frontend)
CREATE POLICY "Permitir inserción pública de eventos" ON public.analytics_events
    FOR INSERT WITH CHECK (true);

-- 5. Permitir lectura solo a usuarios autenticados (admin dashboard)
CREATE POLICY "Permitir select autenticado para eventos" ON public.analytics_events
    FOR SELECT USING (auth.role() = 'authenticated');

-- 6. Vista para resumen del embudo por período
CREATE OR REPLACE VIEW public.funnel_summary AS
SELECT
    event_name,
    COUNT(DISTINCT session_id) AS unique_sessions,
    COUNT(*) AS total_events
FROM public.analytics_events
GROUP BY event_name
ORDER BY
    CASE event_name
        WHEN 'view_catalog' THEN 1
        WHEN 'view_product' THEN 2
        WHEN 'add_to_cart' THEN 3
        WHEN 'initiate_checkout' THEN 4
        WHEN 'purchase' THEN 5
        ELSE 6
    END;
-- Parche SQL: Analíticas y Tracking de Clics
-- ¡Asegúrate de correr esto en el SQL Editor de Supabase para arreglar el contador de clics y fuentes!

-- 1. Añadir columna 'source' para rastrear de dónde vienen los usuarios (Instagram, Facebook, etc).
ALTER TABLE public.page_views ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'direct';

-- 2. Asegurar que los productos tienen una columna para contar clics.
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS click_count INTEGER DEFAULT 0;

-- 3. Crear el procedimiento almacenado (RPC) exacto que usa React para sumar +1 clic en tiempo real.
CREATE OR REPLACE FUNCTION public.increment_click_count(product_id UUID)
RETURNS void AS $$
BEGIN
  UPDATE public.products
  SET click_count = COALESCE(click_count, 0) + 1
  WHERE id = product_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
-- ============================================================
--  Proyecto 3D — Analytics Overhaul v3
--  Ejecutar en el SQL Editor de Supabase
-- ============================================================

-- 1. Columna de visitas completas al detalle del producto
--    (distinta de click_count que sólo cuenta clics en la tarjeta del catálogo)
ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS visit_count INTEGER NOT NULL DEFAULT 0;

-- 2. Vincular cada page_view a un producto específico (para heatmap por producto)
ALTER TABLE public.page_views
  ADD COLUMN IF NOT EXISTS product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL;

-- 3. Índices para consultas rápidas en el dashboard
CREATE INDEX IF NOT EXISTS idx_page_views_created_at  ON public.page_views (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_page_views_product_id  ON public.page_views (product_id);
CREATE INDEX IF NOT EXISTS idx_page_views_source       ON public.page_views (source);
CREATE INDEX IF NOT EXISTS idx_page_views_session      ON public.page_views (session_id);

-- 4. RPC: incrementar visit_count cuando el usuario abre la página de un producto
CREATE OR REPLACE FUNCTION public.increment_visit_count(p_product_id BIGINT)
RETURNS void AS $$
BEGIN
  UPDATE public.products
  SET visit_count = COALESCE(visit_count, 0) + 1
  WHERE id = p_product_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 5. Mantener increment_click_count (para clics en tarjetas del catálogo)
CREATE OR REPLACE FUNCTION public.increment_click_count(product_id BIGINT)
RETURNS void AS $$
BEGIN
  UPDATE public.products
  SET click_count = COALESCE(click_count, 0) + 1
  WHERE id = product_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 6. Vista mensual de tráfico (usable desde el dashboard directamente)
CREATE OR REPLACE VIEW public.monthly_page_views AS
SELECT
  DATE_TRUNC('month', created_at)::DATE AS month,
  source,
  COUNT(DISTINCT session_id)            AS unique_sessions,
  COUNT(*)                              AS total_views
FROM public.page_views
GROUP BY month, source
ORDER BY month DESC;

-- 7. Vista mensual de visitas por producto
CREATE OR REPLACE VIEW public.monthly_product_views AS
SELECT
  DATE_TRUNC('month', pv.created_at)::DATE AS month,
  pv.product_id,
  p.name                                   AS product_name,
  COUNT(*)                                 AS views
FROM public.page_views pv
JOIN public.products p ON p.id = pv.product_id
WHERE pv.product_id IS NOT NULL
GROUP BY month, pv.product_id, p.name
ORDER BY month DESC, views DESC;

-- 8. Asegurar políticas RLS (sin duplicar si ya existen)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'page_views' AND policyname = 'Permitir select autenticado admin'
  ) THEN
    CREATE POLICY "Permitir select autenticado admin" ON public.page_views
      FOR SELECT USING (auth.role() = 'authenticated');
  END IF;
END $$;
-- ============================================================
--  Proyecto 3D — Analytics Fix v4
--  Ejecutar en el SQL Editor de Supabase
--
--  Corrige:
--    1. Tipo de dato de increment_click_count (UUID → BIGINT)
--    2. Vista monthly_product_views usa LEFT JOIN
--    3. Índice compuesto para dashboard
-- ============================================================

-- 0. Asegurar columnas requeridas existen
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS click_count INTEGER DEFAULT 0;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS visit_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE public.page_views ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'direct';
ALTER TABLE public.page_views ADD COLUMN IF NOT EXISTS product_id BIGINT REFERENCES public.products(id) ON DELETE SET NULL;

-- 1. FIX: Eliminar la versión UUID de increment_click_count si existe
--    y asegurar que solo quede la versión BIGINT
DROP FUNCTION IF EXISTS public.increment_click_count(UUID);

CREATE OR REPLACE FUNCTION public.increment_click_count(product_id BIGINT)
RETURNS void AS $$
BEGIN
  UPDATE public.products
  SET click_count = COALESCE(click_count, 0) + 1
  WHERE id = product_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 2. FIX: Asegurar increment_visit_count existe con tipo correcto
CREATE OR REPLACE FUNCTION public.increment_visit_count(p_product_id BIGINT)
RETURNS void AS $$
BEGIN
  UPDATE public.products
  SET visit_count = COALESCE(visit_count, 0) + 1
  WHERE id = p_product_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. FIX: Vista mensual de visitas por producto — usar LEFT JOIN
--    para no excluir page_views sin product_id vinculado
CREATE OR REPLACE VIEW public.monthly_product_views AS
SELECT
  DATE_TRUNC('month', pv.created_at)::DATE AS month,
  pv.product_id,
  COALESCE(p.name, '(sin producto)')       AS product_name,
  COUNT(*)                                  AS views
FROM public.page_views pv
LEFT JOIN public.products p ON p.id = pv.product_id
GROUP BY month, pv.product_id, p.name
ORDER BY month DESC, views DESC;

-- 4. Índice compuesto para optimizar queries del dashboard
CREATE INDEX IF NOT EXISTS idx_page_views_path_created
  ON public.page_views (path, created_at DESC);

-- 5. Permisos: Asegurar que las RPC son ejecutables por anon
GRANT EXECUTE ON FUNCTION public.increment_click_count(BIGINT) TO anon;
GRANT EXECUTE ON FUNCTION public.increment_visit_count(BIGINT) TO anon;

-- 6. RLS: Asegurar que UPDATE anónimo funciona en page_views
--    (necesario para vincular product_id y actualizar duration_seconds)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'page_views' AND policyname = 'Permitir actualizaciones anonimas'
  ) THEN
    CREATE POLICY "Permitir actualizaciones anonimas" ON public.page_views
      FOR UPDATE USING (true);
  END IF;
END $$;

-- 7. FIX CRÍTICO: La SDK de Supabase usa .insert().select().single()
--    que requiere permiso SELECT para devolver el id de la fila insertada.
--    Sin esto, useAnalytics NUNCA recibe el view ID → product_id nunca se vincula.
--    Permitir SELECT anónimo (los datos son anónimos, sin PII sensible).
DO $$
BEGIN
  -- Eliminar la policy vieja que bloquea SELECT para anon
  IF EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'page_views' AND policyname = 'Permitir select autenticado admin'
  ) THEN
    DROP POLICY "Permitir select autenticado admin" ON public.page_views;
  END IF;

  -- Crear policy que permite SELECT tanto a anon (para el .select() post-insert)
  -- como a authenticated (para el dashboard admin)
  CREATE POLICY "Permitir select page_views" ON public.page_views
    FOR SELECT USING (true);
END $$;

-- 8. Asegurar permisos de DELETE en page_views y analytics_events para limpieza
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'page_views' AND policyname = 'Permitir delete anonimo'
  ) THEN
    CREATE POLICY "Permitir delete anonimo" ON public.page_views
      FOR DELETE USING (true);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'analytics_events' AND policyname = 'Permitir delete anonimo'
  ) THEN
    CREATE POLICY "Permitir delete anonimo" ON public.analytics_events
      FOR DELETE USING (true);
  END IF;
END $$;

-- ============================================================================
-- Proyecto 3D — Analytics v5
-- Server-side aggregation + Security hardening
--
-- What this migration does:
--   1. Creates RPC `get_analytics_summary(p_days)` — returns a single JSON
--      object with total views, unique sessions, avg duration, sources,
--      daily views, monthly views (Spanish labels), and top pages.
--   2. Creates RPC `get_funnel_summary(p_days)` — returns a JSON array with
--      unique session counts per funnel event from `analytics_events`.
--   3. Hardens RLS on `page_views` and `analytics_events`:
--      - Drops overly permissive DELETE policies for `anon`.
--      - Adds DELETE restricted to `authenticated` role only.
--      - Keeps INSERT for anon (tracking) and SELECT for all.
--   4. Grants EXECUTE on both RPCs to `anon` and `authenticated`.
--
-- Idempotent: safe to run multiple times (CREATE OR REPLACE, DROP IF EXISTS).
-- ============================================================================

-- --------------------------------------------------------------------------
-- 1. RPC: get_analytics_summary
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_analytics_summary(p_days INT DEFAULT 30)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
AS $$
DECLARE
  _since TIMESTAMPTZ;
  _result JSONB;
BEGIN
  -- When p_days is 0 or NULL, return all-time data (no lower bound).
  IF p_days IS NULL OR p_days = 0 THEN
    _since := '-infinity'::TIMESTAMPTZ;
  ELSE
    _since := now() - (p_days || ' days')::INTERVAL;
  END IF;

  SELECT jsonb_build_object(
    -- Total page views
    'total_views', (
      SELECT COALESCE(COUNT(*), 0)
      FROM public.page_views
      WHERE created_at >= _since
    ),

    -- Unique sessions
    'unique_sessions', (
      SELECT COALESCE(COUNT(DISTINCT session_id), 0)
      FROM public.page_views
      WHERE created_at >= _since
    ),

    -- Average duration (excluding zeros and NULLs)
    'avg_duration', (
      SELECT COALESCE(ROUND(AVG(duration_seconds)), 0)
      FROM public.page_views
      WHERE created_at >= _since
        AND duration_seconds IS NOT NULL
        AND duration_seconds > 0
    ),

    -- Views grouped by traffic source
    'sources', (
      SELECT COALESCE(jsonb_agg(row_to_json(s)::JSONB), '[]'::JSONB)
      FROM (
        SELECT source, COUNT(*) AS views
        FROM public.page_views
        WHERE created_at >= _since
        GROUP BY source
        ORDER BY views DESC
      ) s
    ),

    -- Daily views & unique sessions
    'daily_views', (
      SELECT COALESCE(jsonb_agg(row_to_json(d)::JSONB ORDER BY d.date), '[]'::JSONB)
      FROM (
        SELECT
          created_at::DATE AS date,
          COUNT(*)         AS views,
          COUNT(DISTINCT session_id) AS sessions
        FROM public.page_views
        WHERE created_at >= _since
        GROUP BY created_at::DATE
      ) d
    ),

    -- Monthly views with Spanish month labels
    'monthly_views', (
      SELECT COALESCE(jsonb_agg(row_to_json(m)::JSONB ORDER BY m.month), '[]'::JSONB)
      FROM (
        SELECT
          TO_CHAR(created_at, 'YYYY-MM') AS month,
          (
            CASE EXTRACT(MONTH FROM created_at)
              WHEN  1 THEN 'Ene'
              WHEN  2 THEN 'Feb'
              WHEN  3 THEN 'Mar'
              WHEN  4 THEN 'Abr'
              WHEN  5 THEN 'May'
              WHEN  6 THEN 'Jun'
              WHEN  7 THEN 'Jul'
              WHEN  8 THEN 'Ago'
              WHEN  9 THEN 'Sep'
              WHEN 10 THEN 'Oct'
              WHEN 11 THEN 'Nov'
              WHEN 12 THEN 'Dic'
            END
            || ' ' || EXTRACT(YEAR FROM created_at)::TEXT
          ) AS label,
          COUNT(*)                       AS views,
          COUNT(DISTINCT session_id)     AS sessions
        FROM public.page_views
        WHERE created_at >= _since
        GROUP BY month, label
      ) m
    ),

    -- Top pages by view count (max 20)
    'top_pages', (
      SELECT COALESCE(jsonb_agg(row_to_json(tp)::JSONB), '[]'::JSONB)
      FROM (
        SELECT path, COUNT(*) AS views
        FROM public.page_views
        WHERE created_at >= _since
        GROUP BY path
        ORDER BY views DESC
        LIMIT 20
      ) tp
    )
  ) INTO _result;

  RETURN _result;
END;
$$;

COMMENT ON FUNCTION public.get_analytics_summary(INT) IS
  'Returns a pre-aggregated JSON analytics summary for the last N days. Pass 0 or NULL for all-time data.';


-- --------------------------------------------------------------------------
-- 2. RPC: get_funnel_summary
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_funnel_summary(p_days INT DEFAULT 30)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
AS $$
DECLARE
  _since TIMESTAMPTZ;
  _result JSONB;
BEGIN
  IF p_days IS NULL OR p_days = 0 THEN
    _since := '-infinity'::TIMESTAMPTZ;
  ELSE
    _since := now() - (p_days || ' days')::INTERVAL;
  END IF;

  SELECT COALESCE(
    jsonb_agg(row_to_json(f)::JSONB),
    '[]'::JSONB
  )
  INTO _result
  FROM (
    SELECT
      event_name,
      COUNT(DISTINCT session_id) AS unique_sessions
    FROM public.analytics_events
    WHERE created_at >= _since
    GROUP BY event_name
    ORDER BY unique_sessions DESC
  ) f;

  RETURN _result;
END;
$$;

COMMENT ON FUNCTION public.get_funnel_summary(INT) IS
  'Returns a JSON array of funnel steps with unique session counts from analytics_events.';


-- --------------------------------------------------------------------------
-- 3. RLS Policy Hardening
-- --------------------------------------------------------------------------

-- 3a. page_views ----------------------------------------------------------

-- Drop the overly permissive DELETE policy for anon (if it exists).
DROP POLICY IF EXISTS "Allow anon to delete page_views"   ON public.page_views;
DROP POLICY IF EXISTS "anon_delete_page_views"             ON public.page_views;
DROP POLICY IF EXISTS "Allow anonymous delete"             ON public.page_views;

-- INSERT for anon — needed so the tracker can record page views.
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename  = 'page_views'
      AND policyname = 'anon_insert_page_views'
  ) THEN
    CREATE POLICY anon_insert_page_views ON public.page_views
      FOR INSERT
      TO anon
      WITH CHECK (true);
  END IF;
END $$;

-- SELECT for all roles — needed for .insert().select().single() pattern.
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename  = 'page_views'
      AND policyname = 'select_page_views'
  ) THEN
    CREATE POLICY select_page_views ON public.page_views
      FOR SELECT
      TO public
      USING (true);
  END IF;
END $$;

-- UPDATE for anon — ideally should be restricted to the caller's own
-- session_id, but Supabase anon requests don't carry a trusted session
-- identifier. Keeping this open for now so the client can update
-- duration_seconds on the row it just inserted.
-- TODO: Restrict once a session-auth mechanism is in place.
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename  = 'page_views'
      AND policyname = 'anon_update_page_views'
  ) THEN
    CREATE POLICY anon_update_page_views ON public.page_views
      FOR UPDATE
      TO anon
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;

-- DELETE restricted to authenticated users only (admin cleanup).
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename  = 'page_views'
      AND policyname = 'authenticated_delete_page_views'
  ) THEN
    CREATE POLICY authenticated_delete_page_views ON public.page_views
      FOR DELETE
      TO authenticated
      USING (true);
  END IF;
END $$;

-- 3b. analytics_events ----------------------------------------------------

-- Drop the overly permissive DELETE policy for anon (if it exists).
DROP POLICY IF EXISTS "Allow anon to delete analytics_events"   ON public.analytics_events;
DROP POLICY IF EXISTS "anon_delete_analytics_events"             ON public.analytics_events;
DROP POLICY IF EXISTS "Allow anonymous delete"                   ON public.analytics_events;

-- INSERT for anon — tracking events from the frontend.
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename  = 'analytics_events'
      AND policyname = 'anon_insert_analytics_events'
  ) THEN
    CREATE POLICY anon_insert_analytics_events ON public.analytics_events
      FOR INSERT
      TO anon
      WITH CHECK (true);
  END IF;
END $$;

-- SELECT for all roles.
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename  = 'analytics_events'
      AND policyname = 'select_analytics_events'
  ) THEN
    CREATE POLICY select_analytics_events ON public.analytics_events
      FOR SELECT
      TO public
      USING (true);
  END IF;
END $$;

-- DELETE restricted to authenticated users only (admin cleanup).
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename  = 'analytics_events'
      AND policyname = 'authenticated_delete_analytics_events'
  ) THEN
    CREATE POLICY authenticated_delete_analytics_events ON public.analytics_events
      FOR DELETE
      TO authenticated
      USING (true);
  END IF;
END $$;


-- --------------------------------------------------------------------------
-- 4. Grant EXECUTE on RPCs to anon & authenticated
-- --------------------------------------------------------------------------
GRANT EXECUTE ON FUNCTION public.get_analytics_summary(INT) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.get_funnel_summary(INT)    TO anon, authenticated;


-- ============================================================================
-- Done — Analytics v5 applied.
-- ============================================================================
-- Variantes de color
ALTER TABLE products ADD COLUMN IF NOT EXISTS color_group text;
ALTER TABLE products ADD COLUMN IF NOT EXISTS color_name text;

-- Regalos empresariales
ALTER TABLE products ADD COLUMN IF NOT EXISTS is_corporate boolean DEFAULT false;
ALTER TABLE products ADD COLUMN IF NOT EXISTS corporate_pricing jsonb;
-- Ejemplo de corporate_pricing: [{"min":10,"max":49,"price":8500},{"min":50,"price":7000}]

-- Tabla de leads empresariales (opcional, por ahora vamos por WhatsApp)
-- CREATE TABLE IF NOT EXISTS corporate_leads (
--   id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
--   company_name text NOT NULL,
--   contact_name text,
--   phone text,
--   email text,
--   estimated_qty integer,
--   message text,
--   created_at timestamp DEFAULT now()
-- );
-- ============================================================
--  Proyecto 3D — Sistema de Cupones Dinámicos
--  Ejecutar en el SQL Editor de Supabase
-- ============================================================

-- 1. Tabla de cupones
CREATE TABLE IF NOT EXISTS public.coupons (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    code VARCHAR(50) UNIQUE NOT NULL,
    discount_type VARCHAR(20) NOT NULL CHECK (discount_type IN ('percentage', 'fixed')),
    discount_value NUMERIC NOT NULL,
    min_purchase_amount NUMERIC DEFAULT 0,
    max_uses INTEGER DEFAULT NULL,
    used_count INTEGER DEFAULT 0,
    active BOOLEAN DEFAULT TRUE,
    expires_at TIMESTAMP WITH TIME ZONE,
    applicable_category VARCHAR(100) DEFAULT NULL,
    applicable_product_filter TEXT DEFAULT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Habilitar RLS
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;

-- 3. Política pública de lectura (solo cupones activos y no expirados)
CREATE POLICY "Permitir select público de cupones activos" ON public.coupons
    FOR SELECT USING (active = true AND (expires_at IS NULL OR expires_at > now()));

-- 4. Política de administración completa para usuarios autenticados
CREATE POLICY "Permitir CRUD admin autenticado" ON public.coupons
    FOR ALL USING (auth.role() = 'authenticated');

-- 5. Función para incrementar el uso de un cupón (llamada desde el webhook)
CREATE OR REPLACE FUNCTION public.increment_coupon_usage(p_code TEXT)
RETURNS void AS $$
BEGIN
  UPDATE public.coupons
  SET used_count = used_count + 1
  WHERE code = p_code;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- Semana del Amigo: add promo flag to products table
-- Run this in Supabase SQL Editor before deploying
-- To clean up after the campaign: UPDATE products SET is_friends_week_promo = false;

ALTER TABLE products ADD COLUMN IF NOT EXISTS is_friends_week_promo BOOLEAN DEFAULT false;
-- Corre este script en el SQL Editor de Supabase
-- para permitir múltiples imágenes en la galería de los productos.

ALTER TABLE products 
ADD COLUMN gallery_images TEXT[] DEFAULT '{}';
-- Correr en el Supabase SQL Editor para implementar la base de contactos (Leads)

-- 1. Crear la tabla de leads
CREATE TABLE IF NOT EXISTS public.leads (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    source TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Habilitar RLS (Seguridad)
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;

-- 3. Políticas
-- Permite a cualquiera (público anónimo) INSERTAR un nuevo email
CREATE POLICY "Permitir inserción pública anónima de leads" 
ON public.leads FOR INSERT 
WITH CHECK (true);

-- NO hay política de SELECT pública, los emails capturados solo podrá verlos el Administrador
-- (Asegurate de que tu usuario autenticado o admin tenga permisos para ver todos los datos)
-- SQL Script para recrear la tabla manual_sales con el schema correcto
-- que usa el componente ManualSales.jsx
-- Ejecutar en el SQL Editor de Supabase

-- Eliminar tabla vieja si existe (CUIDADO: borra los datos existentes)
-- Si tenés datos que querés conservar, primero hacé un backup desde Supabase → Table Editor → Export
DROP TABLE IF EXISTS public.manual_sales;

-- Crear tabla con los campos correctos
CREATE TABLE public.manual_sales (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    customer_name   TEXT    NOT NULL,
    customer_phone  TEXT,
    items           TEXT    NOT NULL,
    total_amount    NUMERIC NOT NULL,
    payment_method  TEXT    DEFAULT 'Efectivo',
    status          TEXT    DEFAULT 'paid',
    notes           TEXT,
    created_at      TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.manual_sales ENABLE ROW LEVEL SECURITY;

-- Solo admins autenticados pueden leer/escribir
CREATE POLICY "Admin full access manual_sales"
ON public.manual_sales FOR ALL USING (auth.role() = 'authenticated');
-- Agregar soporte para Emails y Rastreo UTM a la tabla de órdenes

-- Agregar soporte para Rastreo UTM a las visitas
ALTER TABLE public.page_views ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'direct';
-- Run this script in your Supabase SQL Editor

-- 1. Create the orders table
CREATE TABLE public.orders (
    id UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_city TEXT NOT NULL,
    customer_notes TEXT,
    items JSONB NOT NULL,
    total_price DECIMAL(10, 2) NOT NULL,
    status TEXT DEFAULT 'pending' NOT NULL, -- 'pending', 'paid', 'shipped', 'cancelled'
    mp_preference_id TEXT,
    mp_payment_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Setup Row Level Security (RLS)
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- Allow anyone to insert an order (when they initiate checkout)
CREATE POLICY "Anyone can create an order" 
ON public.orders FOR INSERT 
WITH CHECK (true);

-- Allow authenticated admins to view/update all orders
CREATE POLICY "Admins can view and edit orders" 
ON public.orders FOR ALL 
USING (auth.role() = 'authenticated') 
WITH CHECK (auth.role() = 'authenticated');
-- Run this in your Supabase SQL Editor to add promotional price support
ALTER TABLE products ADD COLUMN IF NOT EXISTS promo_price numeric;

-- Optional: set a promo price on a specific product to test
-- UPDATE products SET promo_price = 9500 WHERE name = 'Tu Producto';
-- Correr en el Supabase SQL Editor para implementar el sistema de Reseñas

-- 1. Crear la tabla de reviews
CREATE TABLE IF NOT EXISTS public.reviews (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    product_id BIGINT REFERENCES public.products(id) ON DELETE CASCADE,
    user_name TEXT NOT NULL,
    rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Habilitar RLS (Seguridad)
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

-- Permite a cualquiera (público) LEER las reseñas
CREATE POLICY "Permitir lectura publica de reseñas" 
ON public.reviews FOR SELECT 
USING (true);

-- Permite a cualquiera (público) INSERTAR reseñas (puedes restringirlo despues si tienes auth)
CREATE POLICY "Permitir insersión publica anonima de reseñas" 
ON public.reviews FOR INSERT 
WITH CHECK (true);

-- 3. Crear una vista para obtener los productos junto con su rating promedio
-- Esto evita consultar las reseñas archivo por archivo en el catálogo
CREATE OR REPLACE VIEW products_with_rating AS 
SELECT 
    p.*,
    COALESCE(AVG(r.rating), 0) AS rating_avg,
    COUNT(r.id) AS review_count
FROM 
    public.products p
LEFT JOIN 
    public.reviews r ON p.id = r.product_id
GROUP BY 
    p.id;
-- Ejecutá esto en el SQL Editor de tu cuenta de Supabase
-- para habilitar la subida del Formulario de Productos y las nuevas funciones.

-- 1. Agregar la columna de Stock
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS stock INTEGER;

-- 2. Agregar la columna para las imágenes extra de la galería (Array de textos)
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS gallery_images TEXT[];
-- 1. Agregar la columna de contabilidad de ventas (si no existe)
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS sold_count INTEGER DEFAULT 0;

-- 2. Crear una función (trigger) que se ejecute cuando un pedido se cambie a 'paid'
CREATE OR REPLACE FUNCTION update_product_sold_count()
RETURNS TRIGGER AS $$
DECLARE
    item RECORD;
BEGIN
    -- Only act if the status changes TO 'paid' (or if inserted directly as 'paid')
    IF (TG_OP = 'INSERT' AND NEW.status = 'paid') OR
       (TG_OP = 'UPDATE' AND NEW.status = 'paid' AND OLD.status != 'paid') THEN
       
       -- NEW.items is expected to be a JSONB array, e.g. [{"id": "uuid", "quantity": 1}]
       FOR item IN SELECT * FROM jsonb_array_elements(NEW.items)
       LOOP
           UPDATE public.products
           SET sold_count = COALESCE(sold_count, 0) + (item.value->>'quantity')::int
           WHERE id = (item.value->>'id')::uuid;
       END LOOP;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. Asignar el trigger a la tabla orders
DROP TRIGGER IF EXISTS trg_update_sold_count ON public.orders;
CREATE TRIGGER trg_update_sold_count
AFTER INSERT OR UPDATE ON public.orders
FOR EACH ROW
EXECUTE FUNCTION update_product_sold_count();

ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS customer_email TEXT;
ALTER TABLE public.orders ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'direct';
