-- 1. Crear tabla de productos
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  sub_category TEXT,
  price NUMERIC NOT NULL,
  image_url TEXT,
  quick_add_upsell BOOLEAN DEFAULT false,
  has_free_packaging BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Insertar los productos de prueba iniciales
INSERT INTO products (name, category, sub_category, price, image_url, quick_add_upsell, has_free_packaging) VALUES
('Figura Articulada Dragón', 'Figuras', 'Imperial', 25000, 'https://placehold.co/400x400?text=Figura+Imperial', true, true),
('Figura Busto Iron Man', 'Figuras', 'Torpedo', 22000, 'https://placehold.co/400x400?text=Figura+Torpedo', true, true),
('Figura Groot', 'Figuras', 'Varios', 18000, 'https://placehold.co/400x400?text=Figura+Camionero', true, true),
('Filamento PLA 1KG', 'Filamentos', NULL, 3500, 'https://placehold.co/400x400?text=Filamento+500g', false, false),
('Accesorio Pico de Loro Alpaca', 'Accesorios', NULL, 12000, 'https://placehold.co/400x400?text=Accesorio+Alpaca', false, true),
('Cama Caliente PEI', 'Repuestos', NULL, 35000, 'https://placehold.co/400x400?text=Matera', false, true),
('Impresora Stanley 1L', 'Accesorios', NULL, 85000, 'https://placehold.co/400x400?text=Impresora', false, false),
('Filamento PETG 500g (Cross-sell)', 'Filamentos', NULL, 2000, 'https://placehold.co/400x400?text=Filamento+250g', false, false),
('Accesorio Clásica (Cross-sell)', 'Accesorios', NULL, 5000, 'https://placehold.co/400x400?text=Accesorio+Clasica', false, false);

-- 3. Crear el Bucket de almacenamiento para las fotos de los productos
INSERT INTO storage.buckets (id, name, public) VALUES ('product-images', 'product-images', true);

-- 4. Configurar las políticas de seguridad del bucket (RLS)
-- Permitir a cualquiera ver las imágenes
CREATE POLICY "Public Access" ON storage.objects FOR SELECT TO public USING (bucket_id = 'product-images');
-- Permitir solo a los administradores logueados subir/editar/borrar imágenes
CREATE POLICY "Auth Upload" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'product-images');
CREATE POLICY "Auth Update" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'product-images');
CREATE POLICY "Auth Delete" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'product-images');

-- 5. Opcional: Desactivar RLS en la tabla products para simplificar (o crear políticas similares allí)
-- Ya que esta app usa admin y publico, dejemos las consultas públicas libres
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
