-- 1. Crear tabla de productos
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  sub_category TEXT,
  price NUMERIC NOT NULL,
  image_url TEXT,
  quick_add_upsell BOOLEAN DEFAULT false,
  has_free_packaging BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Insertar los productos de prueba iniciales
INSERT INTO products (name, category, sub_category, price, image_url, quick_add_upsell, has_free_packaging) VALUES
('Mate Imperial de Calabaza', 'Mates', 'Imperial', 25000, 'https://placehold.co/400x400?text=Mate+Imperial', true, true),
('Mate Torpedo Premium', 'Mates', 'Torpedo', 22000, 'https://placehold.co/400x400?text=Mate+Torpedo', true, true),
('Mate Camionero', 'Mates', 'Varios', 18000, 'https://placehold.co/400x400?text=Mate+Camionero', true, true),
('Yerba Mate Suave 500g', 'Yerbas', NULL, 3500, 'https://placehold.co/400x400?text=Yerba+500g', false, false),
('Bombilla Pico de Loro Alpaca', 'Bombillas', NULL, 12000, 'https://placehold.co/400x400?text=Bombilla+Alpaca', false, true),
('Matera de Cuero', 'Materas y Yerberas', NULL, 35000, 'https://placehold.co/400x400?text=Matera', false, true),
('Termo Stanley 1L', 'Accesorios', NULL, 85000, 'https://placehold.co/400x400?text=Termo', false, false),
('Yerba Mate Pequeña 250g (Cross-sell)', 'Yerbas', NULL, 2000, 'https://placehold.co/400x400?text=Yerba+250g', false, false),
('Bombilla Clásica (Cross-sell)', 'Bombillas', NULL, 5000, 'https://placehold.co/400x400?text=Bombilla+Clasica', false, false);

-- 3. Crear el Bucket de almacenamiento para las fotos de los productos
INSERT INTO storage.buckets (id, name, public) VALUES ('product-images', 'product-images', true);

-- 4. Configurar las políticas de seguridad del bucket (RLS)
-- Permitir a cualquiera ver las imágenes
CREATE POLICY "Public Access" ON storage.objects FOR SELECT TO public USING (bucket_id = 'product-images');
-- Permitir solo a los administradores logueados subir/editar/borrar imágenes
CREATE POLICY "Auth Upload" ON storage.objects FOR INSERT TO authenticated WITH CHECK (bucket_id = 'product-images');
CREATE POLICY "Auth Update" ON storage.objects FOR UPDATE TO authenticated USING (bucket_id = 'product-images');
CREATE POLICY "Auth Delete" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'product-images');

-- 5. Opcional: Desactivar RLS en la tabla products para simplificar (o crear políticas similares allí)
-- Ya que esta app usa admin y publico, dejemos las consultas públicas libres
ALTER TABLE products DISABLE ROW LEVEL SECURITY;
